"""empty message

Revision ID: 5b5baa78e8ea
Revises: 947ab205a9c1
Create Date: 2019-08-31 15:42:59.273018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b5baa78e8ea'
down_revision = '947ab205a9c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'is_empty',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    op.alter_column('cart', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'user_id',
               existing_type=sa.BIGINT(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.alter_column('cart', 'is_empty',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    # ### end Alembic commands ###
